services:
  goa-document:
    build: .
    image: goa-document:latest
    restart: always
    ports:
      - "8085:8085"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/goadocumentdb?authSource=admin
      SPRING_SECURITY_OAUTH2_JWK-URI: http://host.docker.internal:8080/api/goa-user/oauth2/jwks
      SPRING_SECURITY_OAUTH2_TOKEN-URI: http://host.docker.internal:8080/api/goa-user/oauth2/token
    extra_hosts:
      - "host.docker.internal:host-gateway"

#> docker compose up --build -d

# Para ver los logs de arranque
#> docker logs -f goa-user